name: 🆕 Update Bilibili Videos

on:
  schedule:
    - cron: '0 */6 * * *'      # Run every 6 hours
  workflow_dispatch: {}        # Manual trigger is also possible

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch & update videos
        env:
          BILIBILI_UID: ${{ secrets.BILIBILI_UID }}
        run: python update_videos.py

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add videos.json last_bvid.txt
          git diff --staged --quiet || \
            (git commit -m "🆕 Sync latest Bilibili videos" && git push)
